"use client";

import React, { useState, useEffect } from "react";

// Hiragana data
const hiraganaData = {
  A: "あ", I: "い", U: "う", E: "え", O: "お",
  Ka: "か", Ki: "き", Ku: "く", Ke: "け", Ko: "こ",
  Sa: "さ", Shi: "し", Su: "す", Se: "せ", So: "そ",
  Ta: "た", Chi: "ち", Tsu: "つ", Te: "て", To: "と",
  Na: "な", Ni: "に", Nu: "ぬ", Ne: "ね", No: "の",
  Ha: "は", Hi: "ひ", Fu: "ふ", He: "へ", Ho: "ほ",
  Ma: "ま", Mi: "み", Mu: "む", Me: "め", Mo: "も",
  Ya: "や", Yu: "ゆ", Yo: "よ",
  Ra: "ら", Ri: "り", Ru: "る", Re: "れ", Ro: "ろ",
  Wa: "わ", Wo: "を", N: "ん",
  Kya: "きゃ", Kyu: "きゅ", Kyo: "きょ",
  Sha: "しゃ", Shu: "しゅ", Sho: "しょ",
  Cha: "ちゃ", Chu: "ちゅ", Cho: "ちょ",
  Pya: "ぴゃ", Pyu: "ぴゅ", Pyo: "ぴょ",
  Gya: "ぎゃ", Gyu: "ぎゅ", Gyo: "ぎょ",
  Bya: "びゃ", Byu: "びゅ", Byo: "びょ"
};

// Katakana data
const katakanaData = {
  A: "ア", I: "イ", U: "ウ", E: "エ", O: "オ",
  Ka: "カ", Ki: "キ", Ku: "ク", Ke: "ケ", Ko: "コ",
  Sa: "サ", Shi: "シ", Su: "ス", Se: "セ", So: "ソ",
  Ta: "タ", Chi: "チ", Tsu: "ツ", Te: "テ", To: "ト",
  Na: "ナ", Ni: "ニ", Nu: "ヌ", Ne: "ネ", No: "ノ",
  Ha: "ハ", Hi: "ヒ", Fu: "フ", He: "ヘ", Ho: "ホ",
  Ma: "マ", Mi: "ミ", Mu: "ム", Me: "メ", Mo: "モ",
  Ya: "ヤ", Yu: "ユ", Yo: "ヨ",
  Ra: "ラ", Ri: "リ", Ru: "ル", Re: "レ", Ro: "ロ",
  Wa: "ワ", Wo: "ヲ", N: "ン",
  Kya: "キャ", Kyu: "キュ", Kyo: "キョ",
  Sha: "シャ", Shu: "シュ", Sho: "ショ",
  Cha: "チャ", Chu: "チュ", Cho: "チョ",
  Pya: "ピャ", Pyu: "ピュ", Pyo: "ピョ",
  Gya: "ギャ", Gyu: "ギュ", Gyo: "ギョ",
  Bya: "ビャ", Byu: "ビュ", Byo: "ビョ"
};

// Kotoba data
const kotobaData = {
  "Kaki": { hiragana: "あし", kanji: "足" },
  "Bermain": { hiragana: "あそびます", kanji: "遊びます" },
  "Kepala": { hiragana: "あたま", kanji: "頭" },
  "Bahaya / Awas": { hiragana: "あぶない", kanji: "危ない" },
  "Berjalan": { hiragana: "あるきます", kanji: "歩きます" },
  "Tidak / Bukan": { hiragana: "いいえ", kanji: "いいえ (kana)" },
  "Saya makan suguhannya": { hiragana: "いただきます", kanji: "頂きます" },
  "Satu": { hiragana: "いち", kanji: "一" },
  "Memasukkan": { hiragana: "いれます", kanji: "入れます" },
  "Indonesia": { hiragana: "インドネシア", kanji: "—" },
  "Bahasa Indonesia": { hiragana: "インドネシアご", kanji: "インドネシア語" },
  "Orang Indonesia": { hiragana: "インドネシアじん", kanji: "インドネシア人" },
  "Menyanyi": { hiragana: "うたいます", kanji: "歌います" },
  "Lahir": { hiragana: "うまれます", kanji: "生まれます" },
  "Menjual": { hiragana: "うります", kanji: "売ります" },
  "Meletakkan": { hiragana: "おきます", kanji: "置きます" },
  "Mendorong": { hiragana: "おします", kanji: "押します" },
  "Perut": { hiragana: "おなか", kanji: "お腹" },
  "Selamat pagi": { hiragana: "おはようございます", kanji: "お早うございます" },
  "Selamat tidur": { hiragana: "おやすみなさい", kanji: "お休みなさい" },
  "Berenang": { hiragana: "およぎます", kanji: "泳ぎます" },
  "Mengembalikan": { hiragana: "かえします", kanji: "返します" },
  "Keluarga": { hiragana: "かぞく", kanji: "家族" },
  "Badan": { hiragana: "からだ", kanji: "体" },
  "Semangat! / Berusahalah": { hiragana: "がんばってください", kanji: "頑張ってください" },
  "Memakai (pakaian)": { hiragana: "きます", kanji: "着ます" },
  "Sembilan": { hiragana: "きゅう", kanji: "九" },
  "Sembilan puluh": { hiragana: "きゅうじゅう", kanji: "九十" },
  "IM JAPAN": { hiragana: "アイム・ジャパン", kanji: "—" },
  "Obat": { hiragana: "くすり", kanji: "薬" },
  "Mulut": { hiragana: "くち", kanji: "口" },
  "Kaos kaki": { hiragana: "くつした", kanji: "靴下" },
  "Menikah": { hiragana: "けっこんします", kanji: "結婚します" },
  "Peserta magang": { hiragana: "けんしゅうせい", kanji: "研修生" },
  "Lima": { hiragana: "ご", kanji: "五" },
  "Lima puluh": { hiragana: "ごじゅう", kanji: "五十" },
  "Menjawab": { hiragana: "こたえます", kanji: "答えます" },
  "Terima kasih sudah makan": { hiragana: "ごちそうさまでした", kanji: "ご馳走様でした" },
  "Mengfotokopi (copy)": { hiragana: "コピーします", kanji: "—" },
  "Susah": { hiragana: "こまります", kanji: "困ります" },
  "Permisi / permintaan izin": { hiragana: "ごめんください", kanji: "御免ください" },
  "Maaf": { hiragana: "ごめんなさい", kanji: "御免なさい" },
  "Selamat siang": { hiragana: "こんにちは", kanji: "今日は" },
  "Selamat malam": { hiragana: "こんばんは", kanji: "今晩は" },
  "Dompet": { hiragana: "さいふ", kanji: "財布" },
  "Selamat tinggal": { hiragana: "さよなら／さようなら", kanji: "左様なら／然様なら" },
  "Tiga": { hiragana: "さん", kanji: "三" },
  "Tiga puluh": { hiragana: "さんじゅう", kanji: "三十" },
  "Berjalan-jalan": { hiragana: "さんぽします", kanji: "散歩します" },
  "Pekerjaan": { hiragana: "しごと", kanji: "仕事" },
  "Permisi / Maaf mengganggu": { hiragana: "しつれいします", kanji: "失礼します" },
  "Meninggal dunia": { hiragana: "しにます", kanji: "死にます" },
  "Diri sendiri": { hiragana: "じぶん", kanji: "自分" },
  "Melakukan": { hiragana: "します", kanji: "—（為ます secara kanji）" },
  "Sepuluh": { hiragana: "じゅう", kanji: "十" },
  "Sebelas": { hiragana: "じゅういち", kanji: "十一" },
  "Sembilan belas": { hiragana: "じゅうきゅう", kanji: "十九" },
  "Lima belas": { hiragana: "じゅうご", kanji: "十五" },
  "Sampai jumpa": { hiragana: "では、また", kanji: "—" },
  "Terima kasih kembali": { hiragana: "（いいえ）どういたしまして", kanji: "—" },
  "Silakan": { hiragana: "どうぞ", kanji: "—" },
  "Terima kasih": { hiragana: "（どうも）ありがとうございます", kanji: "有難うございます" },
  "Berhenti": { hiragana: "とまります", kanji: "止まります" },
  "Teman": { hiragana: "ともだち", kanji: "友達" },
  "Hilang": { hiragana: "なくします", kanji: "無くします" },
  "Korek api": { hiragana: "マッチ", kanji: "—" },
  "Asbak": { hiragana: "はいざら", kanji: "灰皿" },
  "Korek gas": { hiragana: "ライター", kanji: "—" },
  "Meja": { hiragana: "つくえ", kanji: "机" },
  "Kursi": { hiragana: "いす", kanji: "椅子" },
  "Jendela": { hiragana: "まど", kanji: "窓" },
  "Listrik / lampu": { hiragana: "でんき", kanji: "電気" },
  "Saklar": { hiragana: "スイッチ", kanji: "—" },
  "Pintu": { hiragana: "ドア", kanji: "—" },
  "Televisi": { hiragana: "テレビ", kanji: "—" },
  "Radio": { hiragana: "ラジオ", kanji: "—" },
  "Jam": { hiragana: "とけい", kanji: "時計" },
  "Kamera": { hiragana: "カメラ", kanji: "—" },
  "Mobil": { hiragana: "じどうしゃ", kanji: "自動車" },
  "Rumah": { hiragana: "いえ", kanji: "家" },
  "Halaman": { hiragana: "にわ", kanji: "庭" },
  "Perusahaan": { hiragana: "かいしゃ", kanji: "会社" },
  "Kantor": { hiragana: "じむしょ", kanji: "事務所" },
  "Resepsionis": { hiragana: "うけつけ", kanji: "受付" },
  "Lobi": { hiragana: "ロビー", kanji: "—" },
  "Kamar": { hiragana: "へや", kanji: "部屋" },
  "Toilet": { hiragana: "おてあらい", kanji: "お手洗い" },
  "Ruang kelas": { hiragana: "きょうしつ", kanji: "教室" },
  "Kantin": { hiragana: "しょくどう", kanji: "食堂" },
  "Keahlian / Jurusan": { hiragana: "せんもん", kanji: "専門" },
  "Mesin": { hiragana: "きかい", kanji: "機械" },
  "Komputer": { hiragana: "コンピュータ", kanji: "—" },
  "Pagi": { hiragana: "あさ", kanji: "朝" },
  "Siang": { hiragana: "ひる", kanji: "昼" },
  "Malam": { hiragana: "ばん", kanji: "晩" },
  "Jam 00–12 (a.m.)": { hiragana: "ごぜん", kanji: "午前" },
  "Jam 12–24 (p.m.)": { hiragana: "ごご", kanji: "午後" },
  "Stasiun": { hiragana: "えき", kanji: "駅" },
  "Pabrik": { hiragana: "こうじょう", kanji: "工場" },
  "Bank": { hiragana: "ぎんこう", kanji: "銀行" },
  "Rumah sakit": { hiragana: "びょういん", kanji: "病院" },
  "Department store": { hiragana: "デパート", kanji: "—" },
  "Toko buku": { hiragana: "ほんや", kanji: "本屋" },
  "Tempat pangkas rambut": { hiragana: "とこや", kanji: "床屋" },
  "Dunia": { hiragana: "せかい", kanji: "世界" },
  "Asia": { hiragana: "アジア", kanji: "—" },
  "Eropa": { hiragana: "ヨーロッパ", kanji: "—" },
  "Afrika": { hiragana: "アフリカ", kanji: "—" },
  "Jepang": { hiragana: "にほん", kanji: "日本" },
  "Indonesia": { hiragana: "インドネシア", kanji: "—" },
  "China": { hiragana: "ちゅうごく", kanji: "中国" },
  "Korea Selatan": { hiragana: "かんこく", kanji: "韓国" },
  "Malaysia": { hiragana: "マレーシア", kanji: "—" },
  "Thailand": { hiragana: "タイ", kanji: "—" },
  "Filipina": { hiragana: "フィリピン", kanji: "—" },
  "Vietnam": { hiragana: "ベトナム", kanji: "—" },
  "Singapura": { hiragana: "シンガポール", kanji: "—" },
  "Brunei": { hiragana: "ブルネイ", kanji: "—" },
  "Hongkong": { hiragana: "ホンコン", kanji: "香港" },
  "India": { hiragana: "インド", kanji: "—" },
  "Saudi Arabia": { hiragana: "サウジアラビア", kanji: "—" },
  "Australia": { hiragana: "オーストラリア", kanji: "—" },
  "Inggris": { hiragana: "イギリス", kanji: "—" },
  "Jerman": { hiragana: "ドイツ", kanji: "—" },
  "Prancis": { hiragana: "フランス", kanji: "—" },
  "Italia": { hiragana: "イタリア", kanji: "—" },
  "Belanda": { hiragana: "オランダ", kanji: "—" },
  "Spanyol": { hiragana: "スペイン", kanji: "—" },
  "Rusia": { hiragana: "ロシア", kanji: "—" },
  "Amerika": { hiragana: "アメリカ", kanji: "—" },
  "Kanada": { hiragana: "カナダ", kanji: "—" },
  "Buku": { hiragana: "ほん", kanji: "本" },
  "Kamus": { hiragana: "じしょ", kanji: "辞書" },
  "Koran": { hiragana: "しんぶん", kanji: "新聞" },
  "Majalah": { hiragana: "ざっし", kanji: "雑誌" },
  "Kotak": { hiragana: "はこ", kanji: "箱" },
  "Tas": { hiragana: "かばん", kanji: "鞄" },
  "Kunci": { hiragana: "かぎ", kanji: "鍵" },
  "Pensil": { hiragana: "えんぴつ", kanji: "鉛筆" },
  "Bolpoin": { hiragana: "ボールペン", kanji: "—" },
  "Pena": { hiragana: "ペン", kanji: "—" },
  "Buku Catatan": { hiragana: "ノート", kanji: "—" },
  "Kertas": { hiragana: "かみ", kanji: "紙" },
  "Rokok": { hiragana: "たばこ", kanji: "煙草" },
  "Hari ulang tahun": { hiragana: "たんじょうび", kanji: "誕生日" },
  "Pesawat terbang": { hiragana: "ひこうき", kanji: "飛行機" },
  "Kereta super cepat": { hiragana: "しんかんせん", kanji: "新幹線" },
  "Kereta listrik": { hiragana: "でんしゃ", kanji: "電車" },
  "Kereta bawah tanah": { hiragana: "ちかてつ", kanji: "地下鉄" },
  "Taksi": { hiragana: "タクシー", kanji: "-" },
  "Bus": { hiragana: "バス", kanji: "-" },
  "Sepeda": { hiragana: "じてんしゃ", kanji: "自転車" },
  "Berjalan": { hiragana: "あるいて", kanji: "歩いて" },
  "Kapal laut": { hiragana: "ふね", kanji: "船" },
  "Sendirian": { hiragana: "ひとりで", kanji: "一人で" },
  "Bersama teman": { hiragana: "ともだち（と）", kanji: "友達（と）" },
  "Bersama pacar": { hiragana: "かれ（と）", kanji: "彼（と）" },
  "Makan pagi/sarapan": { hiragana: "あさごはん", kanji: "朝ご飯" },
  "Makan siang": { hiragana: "ひるごはん", kanji: "昼ご飯" },
  "Makan malam": { hiragana: "ばんごはん", kanji: "晩ご飯" },
  "Makanan": { hiragana: "たべもの", kanji: "食べ物" },
  "Nasi": { hiragana: "ごはん", kanji: "ご飯" },
  "Roti": { hiragana: "パン", kanji: "-" },
  "Daging": { hiragana: "にく", kanji: "肉" },
  "Ikan": { hiragana: "さかな", kanji: "魚" },
  "Telur": { hiragana: "たまご", kanji: "卵" },
  "Sayur": { hiragana: "やさい", kanji: "野菜" },
  "Buah-buahan": { hiragana: "くだもの", kanji: "果物" },
  "Apel": { hiragana: "りんご", kanji: "林檎" },
  "Jeruk": { hiragana: "みかん", kanji: "蜜柑" },
  "Pisang": { hiragana: "バナナ", kanji: "-" },
  "Anggur": { hiragana: "ぶどう", kanji: "葡萄" },
  "Nanas": { hiragana: "パイナップル", kanji: "-" },
  "Semangka": { hiragana: "すいか", kanji: "西瓜" },
  "Minuman": { hiragana: "のみもの", kanji: "飲み物" },
  "Kopi": { hiragana: "コーヒー", kanji: "-" },
  "Teh": { hiragana: "こうちゃ", kanji: "紅茶" },
  "Teh Jepang": { hiragana: "にほんちゃ", kanji: "日本茶" },
  "Susu sapi": { hiragana: "ぎゅうにゅう", kanji: "牛乳" },
  "Jus": { hiragana: "ジュース", kanji: "-" },
  "Bir": { hiragana: "ビール", kanji: "-" },
  "Whisky": { hiragana: "ウィスキー", kanji: "-" },
  "Sake": { hiragana: "おさけ", kanji: "お酒" },
  "Air": { hiragana: "みず", kanji: "水" },
   "Pakaian (kemeja)": { hiragana: "シャツ", kanji: "-" },
  "Dasi": { hiragana: "ネクタイ", kanji: "-" },
  "Sepatu": { hiragana: "くつ", kanji: "靴" },
  "Obat": { hiragana: "くすり", kanji: "薬" },
  "Bunga": { hiragana: "はな", kanji: "花" },
  "Tukang": { hiragana: "たくみ", kanji: "匠" },
  "Perangko": { hiragana: "きって", kanji: "切手" },
  "Amplop": { hiragana: "ふうとう", kanji: "封筒" },
  "Pos udara": { hiragana: "くうこう", kanji: "空港" },
  "Kartu pos": { hiragana: "はがき", kanji: "葉書" },
  "Kartu pos bergambar": { hiragana: "えはがき", kanji: "絵葉書" },
  "Karcis": { hiragana: "きっぷ", kanji: "切符" },
  "Film": { hiragana: "えいが", kanji: "映画" },
  "Kuliah": { hiragana: "こうぎ", kanji: "講義" },
  "Sumpit": { hiragana: "はし", kanji: "箸" },
  "Sendok": { hiragana: "スプーン", kanji: "-" },
  "Garpu": { hiragana: "フォーク", kanji: "-" },
  "Pisau": { hiragana: "ナイフ", kanji: "-" },
  "Obeng": { hiragana: "ドライバー", kanji: "-" },
  "Kunci pas": { hiragana: "かぎ", kanji: "鍵" },
  "Tang": { hiragana: "ペンチ", kanji: "-" },
  "Gunting": { hiragana: "はさみ", kanji: "鋏" },
  "Keluarga": { hiragana: "かぞく", kanji: "家族" },
  "Saudara (adik/kakak)": { hiragana: "きょうだい", kanji: "兄弟" },
  "Bapak": { hiragana: "おとうさん", kanji: "お父さん" },
  "Ibu": { hiragana: "おかあさん", kanji: "お母さん" },
  "Kakak laki-laki": { hiragana: "おにいさん", kanji: "お兄さん" },
  "Kakak perempuan": { hiragana: "おねえさん", kanji: "お姉さん" },
  "Adik laki-laki": { hiragana: "おとうとさん", kanji: "弟さん" },
  "Adik perempuan": { hiragana: "いもうとさん", kanji: "妹さん" },
  "Orang-orang": { hiragana: "ひとびと", kanji: "人々" },
  "Katalog": { hiragana: "カタログ", kanji: "-" },
  "Laporan": { hiragana: "レポート", kanji: "-" },
  "Uang": { hiragana: "おかね", kanji: "お金" },
  "Gunung": { hiragana: "やま", kanji: "山" },
  "Sungai": { hiragana: "かわ", kanji: "川" },
  "Laut": { hiragana: "うみ", kanji: "海" },
  "Daging babi": { hiragana: "ぶたにく", kanji: "豚肉" },
  "Daging ayam": { hiragana: "とりにく", kanji: "鶏肉" },
  "Masakan": { hiragana: "りょうり", kanji: "料理" },
  "Olah raga": { hiragana: "スポーツ", kanji: "-" },
  "Pingpong / Tenis meja": { hiragana: "ピンポン", kanji: "-" },
  "Tenis": { hiragana: "テニス", kanji: "-" },
  "Sepak bola": { hiragana: "サッカー", kanji: "-" },
  "Ski": { hiragana: "スキー", kanji: "-" },
  "Bisbol / Base ball": { hiragana: "やきゅう", kanji: "野球" },
  "Musik": { hiragana: "おんがく", kanji: "音楽" },
  "Lagu": { hiragana: "うた", kanji: "歌" },
  "Gitar": { hiragana: "ギター", kanji: "-" },
  "Dansa": { hiragana: "ダンス", kanji: "-" },
  "Huruf Kanji": { hiragana: "かんじ", kanji: "漢字" },
  "Huruf Hiragana": { hiragana: "ひらがな", kanji: "平仮名" },
  "Huruf Katakana": { hiragana: "カタカナ", kanji: "片仮名" },
  "Huruf Romawi": { hiragana: "ローマじ", kanji: "ローマ字" },
  "Kantor pos": { hiragana: "ゆうびんきょく", kanji: "郵便局" },
  "Bis surat": { hiragana: "ポスト", kanji: "-" },
  "Restoran": { hiragana: "レストラン", kanji: "-" },
  "Sekolah": { hiragana: "がっこう", kanji: "学校" },
  "Gedung bioskop": { hiragana: "えいがかん", kanji: "映画館" },
  "Passport": { hiragana: "パスポート", kanji: "-" },
  "Taman": { hiragana: "こうえん", kanji: "公園" },
  "Gedung": { hiragana: "たてもの", kanji: "建物" },
  "Laki-laki": { hiragana: "おとこのひと", kanji: "男の人" },
  "Perempuan": { hiragana: "おんなのひと", kanji: "女の人" },
  "Atas": { hiragana: "うえ", kanji: "上" },
  "Bawah": { hiragana: "した", kanji: "下" },
  "Depan": { hiragana: "まえ", kanji: "前" },
  "Belakang": { hiragana: "うしろ", kanji: "後ろ" },
  "Kanan": { hiragana: "みぎ", kanji: "右" },
  "Kiri": { hiragana: "ひだり", kanji: "左" },
  "Dalam": { hiragana: "なか", kanji: "中" },
  "Luar": { hiragana: "そと", kanji: "外" },
  "Antara": { hiragana: "あいだ", kanji: "間" },
  "Cuaca": { hiragana: "てんき", kanji: "天気" },
  "Cerah": { hiragana: "はれ", kanji: "晴れ" },
  "Mendung": { hiragana: "くもり", kanji: "曇り" },
  "Hujan": { hiragana: "あめ", kanji: "雨" },
  "Salju": { hiragana: "ゆき", kanji: "雪" },
  "Rekreasi / Tamasya": { hiragana: "りょこう", kanji: "旅行" },
  "Oleh-oleh": { hiragana: "おみやげ", kanji: "お土産" },
  "Pekerjaan": { hiragana: "しごと", kanji: "仕事" },
  "Guru": { hiragana: "せんせい", kanji: "先生" },
  "Karyawan": { hiragana: "サラリーマン", kanji: "-" },
  "Polisi": { hiragana: "おまわりさん", kanji: "お巡りさん" },
  "Dokter": { hiragana: "おいしゃさん", kanji: "お医者さん" },
  "Ahli mesin / Insinyur": { hiragana: "エンジニア", kanji: "-" },
  "Radio kaset": { hiragana: "ラジオ", kanji: "-" },
  "Garam": { hiragana: "しお", kanji: "塩" },
  "Gula": { hiragana: "さとう", kanji: "砂糖" },
  "Kecap asin": { hiragana: "しょうゆ", kanji: "醤油" },
  "Sabun mandi": { hiragana: "せっけん", kanji: "石鹸" },
  "Handuk": { hiragana: "タオル", kanji: "-" },
  "Pasta gigi": { hiragana: "はみがき", kanji: "歯磨き" },
  "Sikat gigi": { hiragana: "はブラシ", kanji: "歯ブラシ" },
  "Shampo": { hiragana: "シャンプー", kanji: "-" },
  "Payung": { hiragana: "かさ", kanji: "傘" },
  "Pakaian": { hiragana: "ふく", kanji: "服" },
  "Pakaian khas Jepang": { hiragana: "きもの", kanji: "着物" },
  "Wajah": { hiragana: "かお", kanji: "顔" },
  "Rambut": { hiragana: "かみ", kanji: "髪" },
  "Mata": { hiragana: "め", kanji: "目" },
  "Telinga": { hiragana: "みみ", kanji: "耳" },
  "Hidung": { hiragana: "はな", kanji: "鼻" },
  "Mulut": { hiragana: "くち", kanji: "口" },
  "Gigi": { hiragana: "は", kanji: "歯" },
  "Tangan": { hiragana: "て", kanji: "手" },
  "Kaki": { hiragana: "あし", kanji: "足" },
  "Peralatan listrik": { hiragana: "でんきせいひん", kanji: "電気製品" },
  "Lemari es": { hiragana: "れいぞうこ", kanji: "冷蔵庫" },
  "Rice cooker": { hiragana: "すいはんき", kanji: "炊飯器" },
  "Alat penghisap debu": { hiragana: "そうじき", kanji: "掃除機" },
  "Mesin cuci": { hiragana: "せんたくき", kanji: "洗濯機" },
  "Mantel": { hiragana: "マント", kanji: "-" },
  "Jas hujan": { hiragana: "コート", kanji: "-" },
  "Sweater": { hiragana: "セーター", kanji: "-" },
  "Topi": { hiragana: "ぼうし", kanji: "帽子" },
  "Sarung tangan": { hiragana: "てぶくろ", kanji: "手袋" },
   "Syal": { hiragana: "マフラー", kanji: "-" },
  "Perempatan": { hiragana: "こうさてん", kanji: "交差点" },
  "Lampu merah": { hiragana: "しんごう", kanji: "信号" },
  "Hobi": { hiragana: "しゅみ", kanji: "趣味" },
  "Sekolah Bahasa Jepang": { hiragana: "にほんごがっこう", kanji: "日本語学校" },
  "Guru": { hiragana: "せんせい", kanji: "先生" },
  "Renang": { hiragana: "すいえい", kanji: "水泳" },
  "Buku bacaan": { hiragana: "どくしょ", kanji: "読書" },
  "Kamus elektronik": { hiragana: "でんしじしょ", kanji: "電子辞書" },
  "Minyak": { hiragana: "あぶら", kanji: "油" },
  "Pelayan toko": { hiragana: "てんいん", kanji: "店員" },
  "Pesanan": { hiragana: "ちゅうもん", kanji: "注文" },
  "Gedung olahraga": { hiragana: "たいいくかん", kanji: "体育館" },
  "Mahasiswa asing": { hiragana: "りゅうがくせい", kanji: "留学生" },
  "Daging babi": { hiragana: "ぶたにく", kanji: "豚肉" },
  "Tempat informasi": { hiragana: "あんないじょ", kanji: "案内所" },
  "Pasar/tempat penjualan": { hiragana: "うりば", kanji: "売り場" },
  "Beras": { hiragana: "こめ", kanji: "米" },
  "Toko": { hiragana: "みせ", kanji: "店" },
  "Nomor telepon": { hiragana: "でんわばんごう", kanji: "電話番号" },
  "Bunyi": { hiragana: "おと", kanji: "音" },
  "Tamu/pelanggan": { hiragana: "おきゃくさん", kanji: "お客さん" },
  "Kebun binatang": { hiragana: "どうぶつえん", kanji: "動物園" },
  "Hewan": { hiragana: "どうぶつ", kanji: "動物" },
  "Biang lala": { hiragana: "かんらんしゃ", kanji: "観覧車" },
  "Istri orang lain": { hiragana: "ふじん", kanji: "婦人" },
  "Suami orang lain": { hiragana: "ふじん", kanji: "夫人" },
  "Kartu ATM": { hiragana: "キャッシュカード", kanji: "-" },
  "Kartu telepon": { hiragana: "テレホンカード", kanji: "-" },
  "Kaset tape": { hiragana: "テープ", kanji: "-" },
  "Film (kamera)": { hiragana: "フィルム", kanji: "-" },
  "Mesin pengelola kata": { hiragana: "ワープロ", kanji: "-" },
  "Alat pelubang kertas": { hiragana: "ホッチキス", kanji: "-" },
  "Stapler": { hiragana: "ステープラー", kanji: "-" },
  "Lift": { hiragana: "エレベーター", kanji: "-" },
  "Eskalator": { hiragana: "エスカレーター", kanji: "-" },
  "Mesin penjualan karcis": { hiragana: "けんばいき", kanji: "券売機" },
  "Masjid": { hiragana: "モスク", kanji: "-" },
  "Tempat penjualan bumbu": { hiragana: "スパイスコーナー", kanji: "-" },
  "Sandwich": { hiragana: "サンドイッチ", kanji: "-" },
  "Kol/kubis": { hiragana: "キャベツ", kanji: "-" },
  "Sosis": { hiragana: "ソーセージ", kanji: "-" },
  "Udang goreng": { hiragana: "えびフライ", kanji: "-" },
  "Ayam goreng": { hiragana: "フライドチキン", kanji: "-" },
  "Salad": { hiragana: "サラダ", kanji: "-" },
  "Sup": { hiragana: "スープ", kanji: "-" },
  "Mi spageti": { hiragana: "スパゲティ", kanji: "-" },
  "Coca Cola": { hiragana: "コーラ", kanji: "-" },
  "Golf": { hiragana: "ゴルフ", kanji: "-" },
  "Jogging": { hiragana: "ジョギング", kanji: "-" },
  "Soft ball": { hiragana: "ソフトボール", kanji: "-" },
  "Bola voli": { hiragana: "バレーボール", kanji: "-" },
  "Bola basket": { hiragana: "バスケットボール", kanji: "-" },
  "Boling": { hiragana: "ボーリング", kanji: "-" },
  "Kolam renang": { hiragana: "プール", kanji: "-" },
  "Desainer": { hiragana: "デザイナー", kanji: "-" },
  "Jurnalis/wartawan": { hiragana: "ジャーナリスト", kanji: "-" },
  "Kerja sambilan": { hiragana: "アルバイト", kanji: "-" },
  "Golden Week": { hiragana: "ゴールデンウィーク", kanji: "-" },
  "Lemari sewa": { hiragana: "しゅくはく", kanji: "宿泊" },
  "Layanan/servis": { hiragana: "サービス", kanji: "-" },
  "Natal": { hiragana: "クリスマス", kanji: "-" },
  "Karaoke": { hiragana: "カラオケ", kanji: "-" },
  "Klasik": { hiragana: "クラシック", kanji: "-" },
  "Jazz": { hiragana: "ジャズ", kanji: "-" },
  "Humor": { hiragana: "ユーモア", kanji: "-" },
  "Musik pop": { hiragana: "ポップス", kanji: "-" },
  "Musik rock": { hiragana: "ロック", kanji: "-" },
  "Film horor": { hiragana: "ホラー", kanji: "-" },
  "Film misteri": { hiragana: "ミステリー", kanji: "-" },
  "Film aksi": { hiragana: "アクション", kanji: "-" },
  "Film dokumentasi": { hiragana: "ドキュメンタリー", kanji: "-" },
  "Setelan pakaian": { hiragana: "スーツ", kanji: "-" },
  "Sabuk": { hiragana: "ベルト", kanji: "-" },
  "Sepatu boot": { hiragana: "ブーツ", kanji: "-" },
  "Baju terusan": { hiragana: "ワンピース", kanji: "-" },
  "Meter": { hiragana: "メートル", kanji: "-" },
  "Ukuran": { hiragana: "サイズ", kanji: "-" },
  "Aksesori": { hiragana: "アクセサリー", kanji: "-" },
  "Pink": { hiragana: "ピンク", kanji: "-" },
  "Orange": { hiragana: "オレンジ", kanji: "-" },
  "Abu-abu": { hiragana: "グレー", kanji: "-" },
  "Serambi rumah": { hiragana: "ベランダ", kanji: "-" },
  "Visa": { hiragana: "ビザ", kanji: "-" },
  "Diet": { hiragana: "ダイエット", kanji: "-" },
  "Influenza": { hiragana: "インフルエンザ", kanji: "-" },
  "Pom bensin": { hiragana: "ガソリンスタンド", kanji: "-" },
  "Hewan peliharaan": { hiragana: "ペット", kanji: "-" },
  "Panda": { hiragana: "パンダ", kanji: "-" },
  "Menyelam": { hiragana: "ダイビング", kanji: "-" },
  "Klub dansa": { hiragana: "ダンスクラブ", kanji: "-" },
  "Hari Valentine": { hiragana: "バレンタインデー", kanji: "-" },
  "Kalung": { hiragana: "ネックレス", kanji: "-" },
  "Informasi": { hiragana: "インフォメーション", kanji: "-" },
  "Pasar loak": { hiragana: "フリーマーケット", kanji: "-" },
  "Tisu toilet": { hiragana: "トイレットペーパー", kanji: "-" },
  "Jadwal": { hiragana: "スケジュール", kanji: "-" },
  "Home stay": { hiragana: "ホームステイ", kanji: "-" },
  "Tantangan": { hiragana: "チャレンジ", kanji: "-" },
  "Monyet": { hiragana: "サル", kanji: "猿" },
  "Gajah": { hiragana: "ゾウ", kanji: "象" },
  "Pizza": { hiragana: "ピザ", kanji: "-" },
  "Kontes": { hiragana: "コンテスト", kanji: "-" },
  "Jalan-jalan dengan mobil": { hiragana: "ドライブ", kanji: "-" },
  "Komedi": { hiragana: "コメディー", kanji: "-" },
  "Belanja": { hiragana: "ショッピング", kanji: "-" },
  "Game": { hiragana: "ゲーム", kanji: "-" },
  "Poin": { hiragana: "ポイント", kanji: "-" },
  "Barbekyu": { hiragana: "バーベキュー", kanji: "-" },
  "Internet": { hiragana: "インターネット", kanji: "-" },
  "Keju": { hiragana: "チーズ", kanji: "-" },
  "Toko serba 100 yen": { hiragana: "100円ショップ", kanji: "-" },
  "Bangun tidur": { hiragana: "おきます", kanji: "起きます" },
  "Tidur": { hiragana: "ねます", kanji: "寝ます" },
  "Bekerja": { hiragana: "はたらきます", kanji: "働きます" },
  "Istirahat": { hiragana: "やすみます", kanji: "休みます" },
  "Belajar (sendiri)": { hiragana: "べんきょうします", kanji: "勉強します" },
  "Pergi": { hiragana: "いきます", kanji: "行きます" },
  "Datang": { hiragana: "きます", kanji: "来ます" },
  "Pulang": { hiragana: "かえります", kanji: "帰ります" },
  "Makan": { hiragana: "たべます", kanji: "食べます" },
  "Minum": { hiragana: "のみます", kanji: "飲みます" },
  "Menghisap (rokok)": { hiragana: "すいます", kanji: "吸います" },
  "Membaca": { hiragana: "よみます", kanji: "読みます" },
  "Melihat": { hiragana: "みます", kanji: "見ます" },
  "Mendengar": { hiragana: "ききます", kanji: "聞きます" },
  "Menulis": { hiragana: "かきます", kanji: "書きます" },
  "Membeli": { hiragana: "かいます", kanji: "買います" },
  "Memotret": { hiragana: "とります", kanji: "撮ります" },
  "Praktek": { hiragana: "じっしゅうします", kanji: "実習します" },
  "Bermain pingpong": { hiragana: "たっきゅうをします", kanji: "卓球をします" },
  "Memulai": { hiragana: "はじめます", kanji: "始めます" },
  "Selesai": { hiragana: "おわります", kanji: "終わります" },
  "Memerlukan (waktu)": { hiragana: "かかります", kanji: "掛かります" },
  "Memotong": { hiragana: "きります", kanji: "切ります" },
  "Memperbaiki": { hiragana: "しゅうりします", kanji: "修理します" },
  "Memberi": { hiragana: "あげます", kanji: "上げます" },
  "Menerima": { hiragana: "もらいます", kanji: "貰います" },
  "Meminjamkan": { hiragana: "かします", kanji: "貸します" },
  "Meminjam": { hiragana: "かります", kanji: "借ります" },
  "Mengajarkan": { hiragana: "おしえます", kanji: "教えます" },
  "Belajar (bersama)": { hiragana: "ならいます", kanji: "習います" },
  "Mengirim": { hiragana: "おくります", kanji: "送ります" },
  "Sampai / tiba": { hiragana: "つきます", kanji: "着きます" },
  "Menelepon": { hiragana: "でんわします", kanji: "電話します" },
  "Bertemu": { hiragana: "あいます", kanji: "会います" },
  "Ada (benda mati)": { hiragana: "あります", kanji: "有ります" },
  "Mengerti": { hiragana: "わかります", kanji: "分かります" },
  "Ada (benda hidup)": { hiragana: "います", kanji: "居ます" },
  "Mati": { hiragana: "しにます", kanji: "死にます" },
  "Berada (benda hidup)": { hiragana: "います", kanji: "-" },
  "Mencuci pakaian": { hiragana: "せんたくします", kanji: "洗濯します" },
  "Membersihkan": { hiragana: "そうじします", kanji: "掃除します" },
  "Membuat": { hiragana: "つくります", kanji: "作ります" },
  "Mengirim (surat)": { hiragana: "おくります", kanji: "送ります" },
  "Menukar": { hiragana: "かえます", kanji: "換えます" },
  "Bermain": { hiragana: "あそびます", kanji: "遊びます" },
  "Jalan-jalan": { hiragana: "さんぽします", kanji: "散歩します" },
  "Bepergian / Melancong": { hiragana: "りょこうします", kanji: "旅行します" },
  "Meninjau": { hiragana: "けんがくします", kanji: "見学します" },
  "Menikah": { hiragana: "けっこんします", kanji: "結婚します" },
  "Masuk": { hiragana: "はいります", kanji: "入ります" },
  "Keluar": { hiragana: "でます", kanji: "出ます" },
  "Berbicara": { hiragana: "はなします", kanji: "話します" },
  "Mengatakan": { hiragana: "いいます", kanji: "言います" },
  "Menunggu": { hiragana: "まちます", kanji: "待ちます" },
  "Buru-buru": { hiragana: "いそぎます", kanji: "急ぎます" },
  "Memanggil": { hiragana: "よびます", kanji: "呼びます" },
  "Memperlihatkan": { hiragana: "みせます", kanji: "見せます" },
  "Memberitahu": { hiragana: "おしえます", kanji: "教えます" },
  "Mengingat": { hiragana: "おぼえます", kanji: "覚えます" },
  "Turun (hujan)": { hiragana: "ふります", kanji: "降ります" },
  "Mengambil": { hiragana: "とります", kanji: "取ります" },
  "Berdiri": { hiragana: "たちます", kanji: "立ちます" },
  "Duduk": { hiragana: "すわります", kanji: "座ります" },
  "Meletakkan": { hiragana: "おきます", kanji: "置きます" },
  "Membawa": { hiragana: "もちます", kanji: "持ちます" },
  "Menyalakan": { hiragana: "つけます", kanji: "点けます" },
  "Memadamkan / mematikan": { hiragana: "けします", kanji: "消します" },
  "Membuka": { hiragana: "あけます", kanji: "開けます" },
  "Menutup": { hiragana: "しめます", kanji: "閉めます" },
  "Berlari": { hiragana: "はしります", kanji: "走ります" },
  "Berenang": { hiragana: "およぎます", kanji: "泳ぎます" },
  "Menggunakan": { hiragana: "つかいます", kanji: "使います" },
  "Tahu / kenal": { hiragana: "しります", kanji: "知ります" },
  "Tinggal": { hiragana: "すみます", kanji: "住みます" },
  "Menjual": { hiragana: "うります", kanji: "売ります" },
  "Menanggalkan (baju)": { hiragana: "ぬぎます", kanji: "脱ぎます" },
  "Mengembalikan": { hiragana: "かえします", kanji: "返します" },
  "Membayar": { hiragana: "はらいます", kanji: "払います" },
  "Naik": { hiragana: "のぼります", kanji: "登ります" },
  "Turun": { hiragana: "おります", kanji: "降ります" },
  "Berhenti": { hiragana: "とまります", kanji: "止まります" },
  "Berjalan": { hiragana: "あるきます", kanji: "歩きます" },
  "Bermanfaat": { hiragana: "やくにたちます", kanji: "役に立ちます" },
  "Perlu": { hiragana: "いります", kanji: "要ります" },
  "Susah / Bingung": { hiragana: "こまります", kanji: "困ります" },
  "Menghilangkan": { hiragana: "なくします", kanji: "無くします" },
  "Melepas": { hiragana: "ぬぎます", kanji: "脱ぎます" },
  "Menyentuh": { hiragana: "さわります", kanji: "触ります" },
  "Tertawa": { hiragana: "わらいます", kanji: "笑います" },
  "Lupa": { hiragana: "わすれます", kanji: "忘れます" },
  "Memasukkan": { hiragana: "いれます", kanji: "入れます" },
  "Mengeluarkan": { hiragana: "だします", kanji: "出します" },
  "Menghentikan": { hiragana: "とめます", kanji: "止めます" },
  "Khawatir": { hiragana: "しんぱいします", kanji: "心配します" },
  "Berhati-hati": { hiragana: "きをつけます", kanji: "気をつけます" },
  "Membawa pergi": { hiragana: "つれていきます", kanji: "連れて行きます" },
  "Membawa datang": { hiragana: "つれてきます", kanji: "連れて来ます" },
  "Sembuh": { hiragana: "なおります", kanji: "治ります" },
  "Memperbaiki": { hiragana: "なおします", kanji: "直します" },
  "Bermain (piano)": { hiragana: "ひきます", kanji: "弾きます" },
  "Menyanyi": { hiragana: "うたいます", kanji: "歌います" },
  "Berenang": { hiragana: "およぎます", kanji: "泳ぎます" },
  "Menyetir": { hiragana: "うんてんします", kanji: "運転します" },
  "Meminjam": { hiragana: "かります", kanji: "借ります" },
  "Mencuci": { hiragana: "あらいます", kanji: "洗います" },
  "Mandi": { hiragana: "あびます", kanji: "浴びます" },
  "Meninggalkan (rumah)": { hiragana: "でかけます", kanji: "出かけます" },
  "Mengetuk (pintu)": { hiragana: "のっくします", kanji: "ノックします" },
  "Rusak": { hiragana: "こしょうします", kanji: "故障します" },
  "Bertanya": { hiragana: "ききます", kanji: "聞きます" },
  "Menginap": { hiragana: "とまります", kanji: "泊まります" },
  "Berhenti (kerja, sekolah)": { hiragana: "やめます", kanji: "辞めます" },
  "Mengira": { hiragana: "おもいます", kanji: "思います" },
  "Menyeberang": { hiragana: "わたります", kanji: "渡ります" },
  "Belok": { hiragana: "まがります", kanji: "曲がります" },
  "Memperhatikan": { hiragana: "ちゅういします", kanji: "注意します" },
  "Ganti kendaraan": { hiragana: "のりかえます", kanji: "乗り換えます" },
  "Lahir": { hiragana: "うまれます", kanji: "生まれます" },
  "Menggambar": { hiragana: "かきます", kanji: "描きます" },
  "Merakit": { hiragana: "くみたてます", kanji: "組み立てます" },
  "Membongkar": { hiragana: "ぶんかいします", kanji: "分解します" },
  "Menjelaskan": { hiragana: "せつめいします", kanji: "説明します" },
  "Memeriksa": { hiragana: "しらべます", kanji: "調べます" },
  "Berpikir": { hiragana: "かんがえます", kanji: "考えます" },
  "Bergerak": { hiragana: "うごきます", kanji: "動きます" },
  "Menekan / Mendorong": { hiragana: "おします", kanji: "押します" },
  "Menarik": { hiragana: "ひきます", kanji: "引きます" },
  "Menyala": { hiragana: "つきます", kanji: "点きます" },
  "Padam": { hiragana: "きえます", kanji: "消えます" },
  "Kelihatan": { hiragana: "みえます", kanji: "見えます" },
  "Kedengaran": { hiragana: "きこえます", kanji: "聞こえます" },
  "Jadi / Selesai": { hiragana: "なります", kanji: "なります" },
  "Menyetel / Mengeset": { hiragana: "つけかえます", kanji: "付け替えます" },
  "Mengoperasikan": { hiragana: "そうさします", kanji: "操作します" },
  "Makan (bersama)": { hiragana: "いっしょにたべます", kanji: "一緒に食べます" },
  "Putus / Berpisah": { hiragana: "わかれます", kanji: "別れます" },
  "Melarikan diri / Kabur": { hiragana: "にげます", kanji: "逃げます" },
  "Menghitung": { hiragana: "かぞえます", kanji: "数えます" },
  "Berkumpul": { hiragana: "あつまります", kanji: "集まります" },
  "Masuk rumah sakit": { hiragana: "にゅういんします", kanji: "入院します" },
  "Melakukan": { hiragana: "やります", kanji: "やります" },
  "Percaya": { hiragana: "しんじます", kanji: "信じます" },
  "Cukup": { hiragana: "たります", kanji: "足ります" },
  "Mencampur": { hiragana: "まぜます", kanji: "混ぜます" },
  "Mengecek / Mengelap": { hiragana: "ふきます", kanji: "拭きます" },
  "Memeriksa kembali": { hiragana: "てんけんします", kanji: "点検します" },
  "Lembur": { hiragana: "ざんぎょうします", kanji: "残業します" },
  "Memakai topi": { hiragana: "ぼうしをかぶります", kanji: "帽子をかぶります" },
  "Tanggalkan / Mengelap": { hiragana: "ぬげます", kanji: "脱げます" },
  "Menutup mata": { hiragana: "めをとじます", kanji: "目を閉じます" },
  "Mempersiapkan": { hiragana: "じゅんびします", kanji: "準備します" },
  "Berdoa": { hiragana: "いのります", kanji: "祈ります" },
  "Merapikan": { hiragana: "せいりします", kanji: "整理します" },
  "Keluar rumah sakit": { hiragana: "たいいんします", kanji: "退院します" },
  "Senam": { hiragana: "たいそうします", kanji: "体操します" },
  "Meminta maaf": { hiragana: "あやまります", kanji: "謝ります" },
  "Melapor": { hiragana: "ほうこくします", kanji: "報告します" },
  "Menangis": { hiragana: "なきます", kanji: "泣きます" }
  
};

export default function KanaQuiz() {
  const [mode, setMode] = useState("hiragana");
  const [usedKeys, setUsedKeys] = useState([]);
  const [question, setQuestion] = useState("");
  const [options, setOptions] = useState([]);
  const [feedback, setFeedback] = useState("");

  const data = mode === "hiragana" ? hiraganaData : mode === "katakana" ? katakanaData : kotobaData;
  const allKeys = Object.keys(data);

  const generateQuestion = () => {
    const availableKeys = allKeys.filter(k => !usedKeys.includes(k));
    if (availableKeys.length === 0) {
      setQuestion("");
      return;
    }
    const randKey = availableKeys[Math.floor(Math.random() * availableKeys.length)];
    const optionsSet = new Set([randKey]);
    while (optionsSet.size < 4 && optionsSet.size < allKeys.length) {
      optionsSet.add(allKeys[Math.floor(Math.random() * allKeys.length)]);
    }

    setQuestion(mode === "kotoba" ? randKey : data[randKey]);
    setOptions(shuffleArray([...optionsSet]));
  };

  const handleAnswer = (answer) => {
    let correctKey;
    if (mode === "kotoba") {
      correctKey = question;
    } else {
      correctKey = Object.keys(data).find(k => data[k] === question);
    }

    if (answer === correctKey) {
      setFeedback("✅ Benar!");
      setUsedKeys([...usedKeys, correctKey]);
      setTimeout(() => {
        setFeedback("");
        generateQuestion();
      }, 1000);
    } else {
      if (mode === "kotoba") {
        const correct = kotobaData[correctKey];
        setFeedback(`❌ Salah. Jawaban: ${correct.kanji} (${correct.hiragana})`);
      } else {
        setFeedback(`❌ Salah. Jawaban: ${correctKey}`);
      }
      setTimeout(() => setFeedback(""), 1500);
    }
  };

  const shuffleArray = (arr) => arr.sort(() => Math.random() - 0.5);

  useEffect(() => {
    setUsedKeys([]);
    generateQuestion();
  }, [mode]);

  return (
    <div style={{ backgroundColor: "#d1d5db", minHeight: "100vh", padding: "2rem", textAlign: "center", fontFamily: "sans-serif" }}>
      <h1 style={{ fontSize: "2rem", color: "#3b82f6" }}>
        Tebak {mode === "hiragana" ? "Hiragana" : mode === "katakana" ? "Katakana" : "Kotoba"}
      </h1>

      <div style={{ margin: "1rem" }}>
        {["hiragana", "katakana", "kotoba"].map((m) => (
          <button
            key={m}
            onClick={() => setMode(m)}
            style={{
              backgroundColor: mode === m ? "#3b82f6" : "#e5e7eb",
              color: mode === m ? "white" : "#1f2937",
              padding: "0.5rem 1rem",
              borderRadius: "0.5rem",
              marginRight: "0.5rem",
              border: "none"
            }}
          >
            {m.charAt(0).toUpperCase() + m.slice(1)}
          </button>
        ))}
      </div>

      {question ? (
        <>
          <div style={{ fontSize: "2rem", marginBottom: "1rem" }}>{question}</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
            {options.map((opt, idx) => (
              <button
                key={idx}
                onClick={() => handleAnswer(opt)}
                style={{
                  padding: "1rem",
                  fontSize: "1.2rem",
                  backgroundColor: "#f0f9ff",
                  border: "2px solid #3b82f6",
                  borderRadius: "0.5rem",
                  cursor: "pointer"
                }}
                onMouseOver={(e) => e.currentTarget.style.backgroundColor = "#dbeafe"}
                onMouseOut={(e) => e.currentTarget.style.backgroundColor = "#f0f9ff"}
              >
                {mode === "kotoba" ? (
                  <>
                    <div style={{ fontSize: "1.5rem" }}>{kotobaData[opt]?.kanji ?? "?"}</div>
                    <div style={{ fontSize: "1rem", color: "#555" }}>{kotobaData[opt]?.hiragana ?? "?"}</div>
                  </>
                ) : (
                  data[opt]
                )}
              </button>
            ))}
          </div>
          <div style={{ marginTop: "1rem", fontSize: "1.2rem" }}>{feedback}</div>
        </>
      ) : (
        <div style={{ fontSize: "1.2rem", color: "#10b981" }}>🎉 Semua pertanyaan selesai!</div>
      )}
    </div>
  );
}
